name: TFLint

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check_changed:
    outputs:
      directories: ${{ steps.check_directories.outputs.directories }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Check Directories
        id: check_directories
        run: |
          set -x
          changes=$(sed '/^[[:blank:]]*#/d;s/#.*//' "$GITHUB_WORKSPACE/tflint-enabled-directories" | xargs -n1 | while read directory;
          do
              pushd "$GITHUB_WORKSPACE/$directory" > /dev/null
              if [ $(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} . | wc -l) -gt 0 ]; then
                  echo ${directory}
              fi
              popd > /dev/null
          done | jq -R . | jq -n '[inputs]' | jq -c 'map(select(length > 0))')
          echo ::set-output name=directories::$changes
  tflint:
    runs-on: ubuntu-latest
    needs:
      - check_changed
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJSON(needs.check_changed.outputs.directories) }}
    if: needs.check_changed.outputs.directories != '[]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Copy default TFLint config file
        run: cp .tflint.hcl ~/.tflint.hcl

      - uses: actions/cache@v3.3.2
        name: Cache TFLint plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: v1-tflint-${{ hashFiles('.tflint.hcl') }}
          restore-keys: |
            v1-tflint-${{ hashFiles('.tflint.hcl') }}
            v1-tflint-

      - uses: terraform-linters/setup-tflint@v3.1.1
        name: Setup TFLint
        with:
          tflint_version: v0.43.0

      - name: Show version
        run: tflint --version
        working-directory: ./${{ matrix.directory }}

      - name: Init TFLint
        run: tflint --init --loglevel=info
        working-directory: ./${{ matrix.directory }}

      - name: TFLint ${{ matrix.directory }}
        working-directory: ./${{ matrix.directory }}
        run: tflint .